### ISSUE TITLE
Template for "segmented" models

### ISSUE THREAD

**Issue by smmaurer** [UDST/urbansim_templates#28]
Max (@mxndrwgrdnr) requests a template for segmented discrete choice models.

The template would accept standard MNL parameters plus some additional ones detailing the segmentation. It would automatically generate a set of models with identical expressions but different data filters.

This functionality was provided in `urbansim.models.dcm.SegmentedMNLDiscreteChoiceModel` and is used for things like income quartiles or employment sectors (eg [here](https://github.com/psrc/urbansim2/blob/master/configs/elcm.yaml)). 

Users can accomplish the same outcome by creating multiple models with distinct explicit filters, which is easier with `urbansim_templates` than it was before. My sense is that the manual approach is better than the automatic one when there are a small number of segments, because it gives you more control over the models and forces you to explicitly document what break points you're using. But in cases with lots of segments it would certainly be easier to have a template generate them.

**Comment by smmaurer** [comment]
As for implementation, I think we can create a template for this without any changes to ModelManager.

The template could be called `SegmentedLargeMultinomialLogitStep` or something similar. Its core functionality would be to determine how to convert the segmentation instructions into data filters, and then create/estimate/store some number of `LargeMultinomialLogitStep` objects accordingly.

Its parameters would include all of the `LargeMultinomialLogitStep` parameters, which would be passed down to the underlying models (except `name` and `tags`). It would also take one additional parameter: `segmentation_column`. This column in the observations table should contain categorical values that can be used to segment and label the models.

The `SegmentedLargeMultinomialLogitStep` class should implement `from_dict()`, `to_dict()`, `fit()`, `run()`, `register()`, `TEMPLATE_VERSION = 0.1.dev0`, and whatever getters/setters are needed to handle all its parameters.

As a side note, one potential use for segmented models is to divide choosers into quantiles, based on income or something similar. The old UrbanSim implementation of this requires the user to manually create a segmentation column corresponding to the quantiles. Do we want to automate this in the template? We could support both fixed and dynamic break points. Pros are that it would make things easier for the user (don't have to create or update the segmentation assignments) and we can make sure the break points are saved along with the estimation results (sometimes these have gone missing, making it hard to document/interpret the models ex post). Cons are that this use case is already supported pretty well by applying filters to a standard `LargeMultinomialLogitStep`, so i'm not sure how necessary it is.

Here's the older UrbanSim implementation: https://github.com/UDST/urbansim/blob/master/urbansim/models/dcm.py#L1233

**Comment by mxndrwgrdnr** [comment]
Instead of a `model_expression` parameter, the `SegmentedLargeMultinomialLogitStep` template should have a `default_model_expression` parameter that will be used to perform the initial segmented model estimations. Each of the individual model segments would thus initially inherit their own individual `model_expression` parameters from the `default_model_expression` specified in the parent class. However, once these underlying `LargeMultinomialLogitStep` models have been instantiated, they should be exposed and callable by the user, allowing the user to update each model expression individually. The `SegmentedLargeMultinomialLogitStep` group-level class would thus really only serve to 1) instantiate all of the underlying models from a default model expression; 2) manage the individual models; and 3) implement the underlying models as singular model step during simulation.
