### ISSUE TITLE
Ability to use arbitrary template classes with ModelManager

### ISSUE THREAD

**Issue by Gitiauxx** [UDST/urbansim_templates#42]
In modelmananager avoid lines like `import NewSteps` everytime a NewStep is created. 

The idea is that a user should touch the code in modelmanager even he/she creates a NewStep.

**Comment by Gitiauxx** [comment]
A possibility is to create and use a global variable `pipe` that shared between modules.

pipe will track the NewStep by running 'register_modules(globals()) after NewStep is imported in the user code.

See

**Comment by smmaurer** [comment]
For posterity, here's some additional background about this issue:

When ModelManager loads a model step from disk, it needs to have access to the step's template class. 

```py
import OLSRegressionStep

d = <dict representing a configured model step>
model = OLSRegressionStep.from_dict(d)  # generates an OLSRegressionStep object
```

For templates we define within the library, we can just import each of them in `modelmanager.py`. But how can we give ModelManager access to arbitrary third-party templates?

We began discussing this in issue #40, because it was related to the circular imports. (We ended up resolving the circular imports a different way.)

Here's a [diff](https://github.com/UDST/urbansim_templates/compare/remove-circularity...xavier_remove_import) showing the changes in Xavier's branch mentioned above. The solution is to provide a function in `modelmanager` that accepts template definitions as callables. ModelManager then stores these callables alongside "official" templates in a global dict.

**Comment by Gitiauxx** [comment]
1.I changed the names to register_templates and _templates. That seems cleaner.

2.I kept globals dictionary as an input of register_templates, because it avoids the user to add a line 

> modelmanager.register_templates(step)

for each step she imports. globals takes all imports and then sort the ones that are useful. I am not sure what is cleaner. The dictionary approach is less transparent for the users, but also less work. It may depend on how the templates are used.

**Comment by smmaurer** [comment]
Oh, i get it now. I missed that you could just pass `globals()` as the dictionary.

I was asking around in the office, and Eddie had a good idea about an alternate way to implement this: What about using a [decorator](https://jfine-python-classes.readthedocs.io/en/latest/decorators.html) to register template classes?

Template files, both ours and customized ones, would do something like this:

```py
import modelmanager

@modelmanager.template
class MyCustomTemplate()
      ...
```

And ModelManager would define a registration function similar to your current implementation:

```py
def template():
      ...
```

With this in place, `import MyCustomTemplate` in an end user's script would automatically pass it to ModelManager.

This seems worth trying. Here's a code example from Orca: [orca.py#L1011-L1035](https://github.com/UDST/orca/blob/master/orca/orca.py#L1011-L1035)

**Comment by Gitiauxx** [comment]
That will be very elegant. I will try some version of that.

The only drawback is that MyCustomTemplate will need to import modelmanager
and add the decorator, but that is probably ok.

**Comment by Gitiauxx** [comment]
Here is what works
In eachMyCustomTemplate:

`from .. import modelmanager
@modelmanager.register_templates
MyCustomTemplate`

and in modelmanager

`global _templates
_templates = {}

def register_templates(cls):

	_templates[cls.__name__] = cls
	return cls`

And in build_step, return

`return _templates[d['template']].from_dict(d)`

It works pretty well. Thanks, Eddie....
I cannot push it because my branch was forked from remove_circularity.... but if that works for you, I will 

1. Rebranch from the master once you implemented this part of the code
2. Close this issue
3. Add the Machine Learning Templates
4. Work on testing.

**Comment by smmaurer** [comment]
Great, this sounds perfect. I'll put together a quick PR that implements this.
