### ISSUE TITLE
large mnl simulation fails if choosers is a list

### ISSUE THREAD

**Issue by mxndrwgrdnr** [UDST/urbansim_templates#68]
According to the definition of large_mnl, both `choosers` and `out_choosers` can be either string type or list of string type, seen [here](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/large_multinomial_logit.py#L23-L30) and [here](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/large_multinomial_logit.py#L76-L79), respectively. This all works fine until you get to simulation which uses `orca.get_table()` function on choosers/out_choosers to perform the column update and save results, seen [here](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/large_multinomial_logit.py#L524-L527). I'm pretty sure this could be fixed by replacing `orca.get_table()` with a `self._get_df()` call like is done elsewhere in this model class, but perhaps it would be better to create an additional class attribute `model.out_table` to refer specifically to the output table that will store the results, and which can't be a list of tables, and would therefore be distinct from either `model.choosers` or `model.out_choosers`. Any thoughts?

**Comment by mxndrwgrdnr** [comment]
Actually I think the second idea, using a new argument `out_table` is the only one that will work because you cannot call `update_col_from_series` on the output of `_get_df()`.

**Comment by smmaurer** [comment]
Oh, good catch. I think the reasoning we've used in other places is that the first table in a list needs to be the "primary" table, i.e. the one whose rows represent the unit of analysis -- otherwise it's impossible to know how to merge the tables together properly. And in this case, we can assume/require that the output variable goes into the first table.

See [here](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/regression.py#L40-L44) in the OLS docstrings for example. So i guess we need to replace [MNL#L524-L527](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/large_multinomial_logit.py#L524-L527) with something like [TemplateStep#L290-L308](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/models/shared.py#L290-L308) that i wrote for OLS..

**Comment by mxndrwgrdnr** [comment]
Ah, yes, that looks like a more elegant solution. I'll submit the PR.
