### ISSUE TITLE
model step imports are required in order initialize the model manager even if the model step class itself is never explicitly called

### ISSUE THREAD

**Issue by mxndrwgrdnr** [UDST/urbansim_templates#70]
Hey @smmaurer, not sure if this is the intended functionality or not, but it kind of seems like it shouldn't be. I'm currently envisioning what a new **run.py** script might look like in the new template paradigm, and have the basis for one set up [here](https://github.com/ual/activitysynth/blob/master/run.py). The issue is that I don't think I should have to include [line 3](https://github.com/ual/activitysynth/blob/master/run.py#L3), since the `LargeMultinomialLogitStep` class is never actually called in this script. However, my script breaks if I don't because of the way the modelmanager's `_templates` registry gets created and the fact that the modelmanager's `build_step()` method [requires](https://github.com/UDST/urbansim_templates/blob/master/urbansim_templates/modelmanager.py#L105) the registry to be manually populated with whatever template steps are found in the yaml configs. If I don't include line 3, I cannot use `modelmanager.initialize()`. Is there a rationale for it behaving this way?

**Comment by smmaurer** [comment]
Agree -- better not to have to import all the templates explicitly. 

Does it work it you include `import urbansim_templates`? I think that's what we were going for -- the change was in PR #44. As long as the template is imported _somehow_, including as part of a larger library, it should be accessible to the currently running instance of ModelManager.

We had trouble making it fully automatic because the templates use functions from ModelManager. If the modelmanager script also imports the templates, the circularity causes problems on certain python platforms.

**Comment by mxndrwgrdnr** [comment]
Ah OK, that does work. I should have figured that one out. Makes total sense.

**Comment by smmaurer** [comment]
Great. Not sure it makes _total_ sense, since there's no apparent reference to the urbansim_templates library in the script, but it's fairly smooth.
